baseURL = 'https://goropikari.github.io/CompetitiveProgramming/'
languageCode = 'ja'
title = '競プロメモ'
theme = "hyde"

menu.main = [
  { name = "Tags", url = "/tags/", weight = 1 },
  { name = "Rating Calculator", url = "/rating/", weight = 2 },
  { name = "Algorithm", url = "/algorithm/", weight = 3 },
]

menu.atcoder = [
  { name = "ABC", url = "/tags/abc", weight = 1 },
  { name = "ARC", url = "/tags/arc", weight = 2 },
]

[taxonomies]
  tag = "tags"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
