version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: "julia -e 'using Pkg; Pkg.activate(\".\"); Pkg.instantiate(); using Franklin; serve(host=\"0.0.0.0\")'"
