name: Update Submissions and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 毎日の午前0時に実行(UTC)

permissions:
  contents: write
  pull-requests: write

jobs:
  update-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run script
        run: |
          python scripts/submissions.py
          python scripts/stat.py

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-submissions-${{ env.date }}
          commit-message: "Update submissions data"
          title: "Update submissions data"
          body: "This PR updates submissions data by running submissions.py"

      - name: Merge PR
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --rebase ${{ steps.pr.outputs.pull-request-url }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
