name: Update problems and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜日の午前0時に実行(UTC)

permissions:
  contents: write
  pull-requests: write

jobs:
  update-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run script
        run: python scripts/problem_models.py

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-problems-${{ env.date }}
          commit-message: "Update problems data"
          title: "Update problems data"
          body: "This PR updates problems data by running problems.py"

      - name: Merge PR
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --rebase ${{ steps.pr.outputs.pull-request-url }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
